version: '3.5'
name: 'lab'

services:
  app:
    image: "${APP_IMAGE}"
    container_name: "${APP_NAME}"
    build:
      context: .
      dockerfile: Dockerfile
      args:
        USERNAME: "${USERNAME}"
    env_file: .env
    ports:
      - "${SSH_PORT}:22"
    volumes:
      - "./conf/user/.ssh:/home/${USERNAME}/.ssh"
    networks:
      - proxy
    logging:
      options:
        max-size: 50m
        max-file: '10'
    restart: always
    tty: true
    init: true

networks:
  proxy:
    name: "${APP_NETWORK}"
